nelmio_api_doc:
    documentation:
        info:
            title: PHP Tasks Manager - TasksService
            description: PHP Tasks Manager - TasksService
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
